CREATE DATABASE DISC;

CREATE TABLE GAMECHARACTERS (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    HP INT
);

CREATE TABLE COMMENT (
    ID integer primary key not null AUTO_INCREMENT,
    TEXT varchar(50),
    GAMECHARACTER_ID integer,
    CONSTRAINT gamecharacter_fk FOREIGN KEY (GAMECHARACTER_ID) REFERENCES GAMECHARACTERS(ID)
);